### ISSUE TITLE
Neutron network query needs filter parameters

### ISSUE THREAD

**Issue by wallyworld** [go-goose/goose#38]
When allocating a public IP using the AllocatePublicIP() API, we use the neutron network API to query networks, and subsequently go through the result to look for networks matching availability zones.

We use the API  "GET /v2.0/networks"  which should return all networks.

However, some Openstacks require a query param to explicitly ask for external networks:

GET  /v2.0/networks?router:external=True

We need to tweak the neutron.GetNetworkV2() method to take query params and then modify the getExternalNeutronNetworksByAZ() method to pass in router:external=True

**Comment by markramm** [comment]
What is the status of this issue?

**Comment by hmlanigan** [comment]
Here is a PR: https://github.com/go-goose/goose/pull/41

**Comment by hmlanigan** [comment]
Code has merged, closing
